#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server:
  port: 8080
spring:
  datasource:
    username: root
    password: RooT2024PasS
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
indexing-settings:
  sites:
    - url: https://playback.ru
      name: PlayBack.Ru
    - url: https://ipfran.ru
      name: ipfran.ru
    - url: https://et-cetera.ru
      name: et-cetera.ru

